start:
	docker-compose up

stop:
	docker-compose down
	# or just Ctrl-C in the terminal

reset:
	# Clears out containers, volume mount
	docker-compose down -v --remove-orphans	
	# from separate terminal, or after exiting e.g. w/Ctrl-C
	